/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YearbookRouteImport } from './routes/yearbook'
import { Route as IndexRouteImport } from './routes/index'

const YearbookRoute = YearbookRouteImport.update({
  id: '/yearbook',
  path: '/yearbook',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/yearbook': typeof YearbookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/yearbook': typeof YearbookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/yearbook': typeof YearbookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/yearbook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/yearbook'
  id: '__root__' | '/' | '/yearbook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  YearbookRoute: typeof YearbookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yearbook': {
      id: '/yearbook'
      path: '/yearbook'
      fullPath: '/yearbook'
      preLoaderRoute: typeof YearbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  YearbookRoute: YearbookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
